### ISSUE TITLE
Add alpha channel to the Daedalus sprite sheet.

### ISSUE THREAD

**Issue by pniedzielski** [imaginary-rpg/imaginary-rpg#5]
Our engine now supports reading an alpha channel from a bitmap (PNG format, which we are using).  The pink part can be given an alpha channel.

**Comment by DeadSuperHero** [comment]
Fair enough. I usually just make use of a solid unused color for sprite composition and frame dimensions in animation, but if the pink is a problem, I can try out a different method that just makes use of alpha channels.

**Comment by pniedzielski** [comment]
It's more that, since PNG supports transparency, we can use it in the engine without changing any code on a per-image basis, to say "pink is the transparent color".  This way, we can even have partial transparency without any modification to the code.

**Comment by DeadSuperHero** [comment]
The only concern I have with this is that creating pixel art is usually best done in a bitmapping program, such as Kolourpaint, but bitmapping programs usually have somewhat limited support for working with alpha transparencies. While I can always adapt my work in GIMP, removing a backdrop takes time, and working completely without one (while doable) adds some steps to getting sprite art put together. 

Is it hypothetically possible to have a small amount of code that says "When checking any sprite sheet, whatever the majority color of the sheet is, is automatically deemed transparent?"

If not, that's totally okay, I'll figure out how to improve my current process of making sprites.

**Comment by pniedzielski** [comment]
It can be done at the end, right?

I'll see if I can some code for the majority color of the image to be given a full alpha channel; I don't think that should be too hard.
